CREATE TABLE business.customers (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    name VARCHAR(100) NOT NULL,
                                    email VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE business.orders (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 order_number VARCHAR(40) NOT NULL UNIQUE,
                                 customer_id BIGINT NOT NULL REFERENCES business.customers(id),

                                 product_type VARCHAR(20) NOT NULL
                                     CHECK (product_type IN ('PRINTER', 'INK', 'PAPER')),

                                 product_name VARCHAR(150) NOT NULL,
                                 quantity INTEGER NOT NULL CHECK (quantity > 0),
                                 total_amount NUMERIC(12, 2) NOT NULL CHECK (total_amount >= 0),
                                 currency VARCHAR(3) NOT NULL CHECK (currency ~ '^[A-Z]{3}$'),

    status VARCHAR(20) NOT NULL
        CHECK (status IN ('PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED')),

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    UNIQUE (id, customer_id)
);

CREATE TABLE business.shipments (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    order_id BIGINT NOT NULL UNIQUE REFERENCES business.orders(id),
                                    tracking_id VARCHAR(40) NOT NULL UNIQUE,
                                    carrier VARCHAR(80) NOT NULL,

                                    status VARCHAR(20) NOT NULL
                                        CHECK (status IN ('PENDING', 'IN_TRANSIT', 'DELAYED', 'DELIVERED')),

                                    estimated_delivery_date DATE NOT NULL,
                                    delivered_date DATE,
                                    delay_reason VARCHAR(500),
                                    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                    CHECK (status <> 'DELAYED' OR delay_reason IS NOT NULL),
                                    CHECK ((status = 'DELIVERED') = (delivered_date IS NOT NULL))
);

CREATE TABLE business.subscriptions (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        customer_id BIGINT NOT NULL REFERENCES business.customers(id),
                                        source_order_id BIGINT NOT NULL UNIQUE,

                                        product_type VARCHAR(20) NOT NULL
                                            CHECK (product_type IN ('PRINTER', 'INK', 'PAPER')),

                                        plan_name VARCHAR(100) NOT NULL,

                                        billing_cycle VARCHAR(20) NOT NULL
                                            CHECK (billing_cycle IN ('MONTHLY', 'QUARTERLY', 'ANNUAL')),

                                        status VARCHAR(20) NOT NULL
                                            CHECK (status IN ('ACTIVE', 'PAUSED', 'CANCELLED')),

                                        recurring_amount NUMERIC(12, 2) NOT NULL
                                            CHECK (recurring_amount >= 0),

                                        currency VARCHAR(3) NOT NULL CHECK (currency ~ '^[A-Z]{3}$'),
    start_date DATE NOT NULL,
    next_billing_date DATE,
    minimum_term_end_date DATE,
    cancelled_date DATE,

    FOREIGN KEY (source_order_id, customer_id)
        REFERENCES business.orders(id, customer_id),

    CHECK (next_billing_date IS NULL OR next_billing_date >= start_date),
    CHECK (minimum_term_end_date IS NULL OR minimum_term_end_date >= start_date),
    CHECK (cancelled_date IS NULL OR cancelled_date >= start_date),
    CHECK ((status = 'CANCELLED') = (cancelled_date IS NOT NULL)),
    CHECK (status <> 'CANCELLED' OR next_billing_date IS NULL)
);

CREATE INDEX idx_orders_customer_created
    ON business.orders(customer_id, created_at DESC, id DESC);

CREATE INDEX idx_subscriptions_customer_id
    ON business.subscriptions(customer_id, id);