server:
  address: ${BUSINESS_API_HOST:127.0.0.1}
  port: ${BUSINESS_API_PORT:8081}
  error:
    include-message: never
    include-stacktrace: never

spring:
  application:
    name: business-service

  config:
    import: "optional:file:../.env[.properties]"

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:127.0.0.1}:${POSTGRES_PORT:5433}/${POSTGRES_DB:order_support}
    username: ${POSTGRES_USER:support_app}
    password: ${POSTGRES_PASSWORD}

    hikari:
      maximum-pool-size: 5
      connection-timeout: 5000
      data-source-properties:
        connectTimeout: 5
        socketTimeout: 10

  jdbc:
    template:
      query-timeout: 5s

  flyway:
    enabled: true
    schemas: business
    default-schema: business
    locations: classpath:db/migration
    clean-disabled: true
    validate-migration-naming: true

  sql:
    init:
      mode: never

  mvc:
    problemdetails:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: never
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState,db